#pragma once

#include "CoreMinimal.h"
#include "HL2BlockoutBase.h"

#include "HL2NeighborhoodsBlockout.generated.h"

/**
 * Optional second blockout: overgrown, storybook-style neighbourhoods built
 * into the rubble of an old city, arranged around a central market hub.
 *
 * Six pathways leave the hub (Lantern Road, Tram Steps, Rubble Row, Canal
 * Walk, Windmill Path, Grove Path). The road network has six roads, three
 * T-junctions and three cul-de-sacs, ~30 solid (non-enterable) houses,
 * placeholder blockers, upgrade ledges and hidden rooms. Gameplay spots are
 * shown with the Marker palette entry only; no gameplay is implemented.
 *
 * Authored in Hammer units (1 HU = 1.905 cm) and rebuilt in OnConstruction.
 */
UCLASS()
class HL2BLOCKOUT_API AHL2NeighborhoodsBlockout : public AHL2BlockoutBase
{
	GENERATED_BODY()

public:
	AHL2NeighborhoodsBlockout();

	/** In the hub, facing the great tree. */
	virtual FTransform GetPlayerStartTransform() const override;

	/** Houses generated by the last rebuild. */
	UPROPERTY(VisibleAnywhere, Transient, Category = "HL2 Blockout|Stats")
	int32 HouseCount = 0;

	/** Hidden rooms generated by the last rebuild. */
	UPROPERTY(VisibleAnywhere, Transient, Category = "HL2 Blockout|Stats")
	int32 HiddenRoomCount = 0;

	/** Placeholder path blockers generated by the last rebuild. */
	UPROPERTY(VisibleAnywhere, Transient, Category = "HL2 Blockout|Stats")
	int32 BlockerCount = 0;

protected:
	virtual void BuildLayout() override;

private:
	enum EHouseFeature : uint32
	{
		HF_None = 0,
		HF_Tower = 1 << 0,
		HF_Dormer = 1 << 1,
		HF_Chimney = 1 << 2,
		HF_Balcony = 1 << 3,
		HF_Ivy = 1 << 4,
		/** A scrap-built shack perched on the roof (found architecture). */
		HF_Stacked = 1 << 5,
		/** Half-buried in a rubble mound with a fallen slab leaning on it. */
		HF_Rubble = 1 << 6,
		/** Gable faces the street instead of running along it. */
		HF_GableFront = 1 << 7,
		HF_Fence = 1 << 8,
	};

	/**
	 * Local house frame: origin at the middle of the front wall on the ground,
	 * local +X along the frontage, local +Y into the house.
	 * Facing: 0 = front faces -Y, 1 = +X, 2 = +Y, 3 = -X.
	 */
	struct FFrame
	{
		FVector2D Origin;
		int32 Facing;
		float BaseZ;

		FVector ToWorld(const FVector& Local) const;
	};

	struct FHouse
	{
		FVector2D FrontCenter;
		int32 Facing;
		float Width;
		float Depth;
		int32 Storeys;
		EHL2BlockoutMaterial Wall;
		EHL2BlockoutMaterial Roof;
		uint32 Features;
		uint32 Seed;
		float BaseZ = 0.0f;
	};

	/** World-space XY footprints of the generated houses (for overlap checks). */
	TArray<FBox2D> HouseFootprints;

	void BuildGround();
	void BuildPerimeter();
	void BuildHub();
	void BuildNorthSuburbs();
	void BuildClocktowerHill();
	void BuildRubbleTerraces();
	void BuildFallenBlockAndQuarry();
	void BuildCanalQuarter();
	void BuildGrove();
	void BuildWindmillFields();
	void BuildSkyline();

	void LBox(const FFrame& F, EHL2BlockoutMaterial Mat, const FVector& LocalMin, const FVector& LocalMax);
	void LOriented(const FFrame& F, EHL2BlockoutMaterial Mat, const FVector& LocalCenter, const FVector& Size, const FRotator& LocalRotation);
	void LCylinder(const FFrame& F, EHL2BlockoutMaterial Mat, const FVector& LocalBase, float Radius, float Height);
	/** Gable roof in local space; ridge along local X when bRidgeAlongX. */
	void LRoof(const FFrame& F, EHL2BlockoutMaterial Mat, const FVector& LocalMin, const FVector& LocalMax, bool bRidgeAlongX, int32 Steps);

	void House(const FHouse& Spec);
	/** Narrow terraced building used for the hub's market frontage. */
	void TownBlock(const FFrame& F, float X0, float X1, uint32 Seed, bool bWorkshop);
	/** Row of TownBlocks along local X from X0 to X1, leaving the openings (local X ranges) clear. */
	void TownRow(const FFrame& F, float X0, float X1, const TArray<FVector2D>& Openings, uint32 Seed);

	/** Asphalt (or Tile) road with raised sidewalks. Gaps are ranges along the road with no sidewalk on that side. */
	void Road(bool bAlongX, float Center, float From, float To, EHL2BlockoutMaterial Surface,
		const TArray<FVector2D>& GapsNegSide, const TArray<FVector2D>& GapsPosSide);
	void CulDeSac(const FVector2D& Center, float Radius, float EntryYawDeg);
	void DirtPath(const FVector2D& Min, const FVector2D& Max);

	/** Impassable boundary: Style 0 = hedge, 1 = rubble ridge, 2 = overgrown cliff. */
	void Ridge(const FVector2D& Min, const FVector2D& Max, float Height, int32 Style);
	void Tree(const FVector& Base, float Scale, uint32 Seed);
	void Shrub(const FVector& Base, float Size, uint32 Seed);
	void RubblePile(const FVector& Center, float Radius, float Height, uint32 Seed);
	void Lantern(const FVector& Base);
	/** Jittered trees, shrubs and grass tufts over a rectangle, skipping Avoid boxes and houses. */
	void Scatter(const FVector2D& Min, const FVector2D& Max, float Spacing, float TreeChance, const TArray<FBox2D>& Avoid, uint32 Seed, float BaseZ = 0.0f);

	/** Small enclosed room with a crouch-only (44 HU) entrance. Side: 0 = -X, 1 = +X, 2 = -Y, 3 = +Y. */
	void HiddenRoom(EHL2BlockoutMaterial Mat, const FVector& Min, const FVector& Max, int32 EntranceSide, float EntranceCenter);
	/** Marker sign post standing next to a placeholder blocker. */
	void BlockerSign(const FVector& Base);
	/** Placeholder maintenance robot (Marker) at a blocker. */
	void MaintenanceRobot(const FVector& Base, float Yaw);
	/** Marker stripe on the lip of an upgrade-gated ledge. */
	void LedgeStripe(const FVector& Min, const FVector& Max);
};
